### ISSUE TITLE
Fatal error, undefined function pmpro_getMembershipLevelForUser

### ISSUE THREAD

**Issue by andrewmarino** [unitymakesus/ncaudiology#9]
`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function App\pmpro_getMembershipLevelForUser() in /Users/andrewmarino/Local/nc-audiology/app/public/wp-content/themes/unity-child/app/pmpro-dashboard.php on line 7`

**Comment by isabisa** [comment]
BYEEEEEE PMPRO!
